# Generated by Django 2.1.7 on 2021-07-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, upload_to='blog')),
            ],
        ),
        migrations.CreateModel(
            name='DelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('price_mon', models.IntegerField(default=0)),
                ('price_year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proimg', models.ImageField(blank=True, upload_to='hotel_images')),
                ('no', models.CharField(max_length=50)),
                ('pro_name', models.CharField(default='webdeity', max_length=100)),
                ('prolink', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='service')),
            ],
        ),
        migrations.AddField(
            model_name='delplan',
            name='plan_n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.Plans'),
        ),
    ]
