# Generated by Django 2.1.7 on 2021-07-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog',
            field=models.CharField(default='blog', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titel',
            field=models.CharField(max_length=200),
        ),
    ]
